[tool.poetry]
name = "densitysurf"
version = "0.1.0"
description = ""
authors = ["kristenfeher <kristenmf@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.22"
scipy = "^1.14.1"
scikit-learn = "^1.5.2"
numba = "^0.60.0"
umap-learn = "^0.5.6"
igraph = "^0.11.6"
pandas = "^2.2.3"
scikit-network = "^0.33.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
